package com.bank.bian.corporatetreasury;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Corporate Treasury
 *
 * Business Area:      Business Support
 * Business Domain:    Finance
 * Functional Pattern: Manage
 * Asset Type:         Treasury Plan
 * Control Record:     Treasury Plan Management Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Corporate Treasury — BIAN Semantic API")
                .description("Service Domain 'Corporate Treasury' (Manage pattern) "
                        + "operating on the 'Treasury Plan Management Plan' control record.")
                .version("0.1.0"));
    }
}
